---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops
  namespace: bentonamespace
  labels:
    app: gitops
  annotations:
    fluxcd.io/automated: 'true'
spec:
  selector:
    matchLabels:
      app: gitops
  template:
    metadata:
      labels:
        app: gitops
    spec:
      containers:
      - name: gitops
        image: hello-world
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
