# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python app

on:
  pull_request:
    paths:
    - 'python/*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: push docker image
      run: |
        cd ./python
        docker login --username={{ sercrets.DOCKER_USER }} --password={{ secret.DOCKER_PASSWD }}
        docker image build -t {{ secrets.DOCKER_USER }}/gitops:test1.0 .
        docker push {{ secret.DOCKER_USER }}/gitops:test1.0
